DELETE DATA {
<http://environment.data.gov.uk/def/bathing-water-profile/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Ontology> .
<http://environment.data.gov.uk/def/bathing-water-profile/> <http://purl.org/dc/terms/created> "2011-09-16"^^<http://www.w3.org/2001/XMLSchema#date> .
<http://environment.data.gov.uk/def/bathing-water-profile/> <http://purl.org/dc/terms/modified> "2010-09-16"^^<http://www.w3.org/2001/XMLSchema#date> .
<http://environment.data.gov.uk/def/bathing-water-profile/> <http://purl.org/dc/terms/license> <http://www.opendatacommons.org/licenses/pddl/1.0/> .
<http://environment.data.gov.uk/def/bathing-water-profile/> <http://www.w3.org/2002/07/owl#versionInfo> "0.1"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://environment.data.gov.uk/def/bathing-water-profile/zoiDescription> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/zoiDescription> <http://www.w3.org/2000/01/rdf-schema#label> "zone of influence description"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/zoiDescription> <http://www.w3.org/2000/01/rdf-schema#comment> "zoiDescription is used to relate a bathing water profile to a physical description of the surrounding catchment impacting on the bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/zoiDescription> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/macroAlgaeStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/macroAlgaeStatement> <http://www.w3.org/2000/01/rdf-schema#label> "seaweed statement" .
<http://environment.data.gov.uk/def/bathing-water-profile/macroAlgaeStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "macroAlgaeStatement is used to relate a bathing water profile to a brief statement about Macroalgae (seaweed) at a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/macroAlgaeStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithFarmersStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithFarmersStatement> <http://www.w3.org/2000/01/rdf-schema#label> "working with farmers statement" .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithFarmersStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "workingWithFarmersStatement is used to relate a bathing water profile to a statement about details of any work or improvements to water quality undertaken with local farmers which may impact on a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithFarmersStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/printResImage> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/printResImage> <http://www.w3.org/2000/01/rdf-schema#label> "print resolution image" .
<http://environment.data.gov.uk/def/bathing-water-profile/printResImage> <http://www.w3.org/2000/01/rdf-schema#comment> "printResImage relates a bathing water profile to an image of the bathing water at a resolution suitable for printing."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/printResImage> <http://www.w3.org/2000/01/rdf-schema#domain> <http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> .
<http://environment.data.gov.uk/def/bathing-water-profile/printResImage> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/bathingWaterDescription> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/bathingWaterDescription> <http://www.w3.org/2000/01/rdf-schema#label> "bathing water description"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/bathingWaterDescription> <http://www.w3.org/2000/01/rdf-schema#comment> "bathingWaterDescription relates a resource to a physical description of a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/bathingWaterDescription> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/phytoplanktonStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/phytoplanktonStatement> <http://www.w3.org/2000/01/rdf-schema#label> "phytoplankton statement" .
<http://environment.data.gov.uk/def/bathing-water-profile/phytoplanktonStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "phytoplanktonStatement is used to relate a bathing water profile to a brief statement about Phytoplankton at a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/phytoplanktonStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsGeneralStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#label> "emergency and storm overflow outfalls general statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "esoOutfallsGeneralStatement is used to relate a standard language collection to a brief statement about Emergency outfalls and Storm overflow outfalls."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/latestBathingWaterProfile> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/latestBathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#label> "latest profile"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/latestBathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#comment> "latestBathingWaterProfile is used to relate a bathing water to its latest bathing water profile."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/latestBathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#range> <http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> .
<http://environment.data.gov.uk/def/bathing-water-profile/latestBathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsGeneralStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#label> "sewage treament works outfalls general statement" .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "stwOutfallsGeneralStatement is used to relate a standard language collection to a brief general statement of the improvements to sewage treatment outfalls."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/historyStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/historyStatement> <http://www.w3.org/2000/01/rdf-schema#label> "history statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/historyStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "historyStatement is used to relate a bathing water profile to a statement about details of the history of any water company assets which impact a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/historyStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/webResImage> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/webResImage> <http://www.w3.org/2000/01/rdf-schema#label> "web resolution image" .
<http://environment.data.gov.uk/def/bathing-water-profile/webResImage> <http://www.w3.org/2000/01/rdf-schema#comment> "webResImage relates a bathing water profile to an image of the bathing water at a resolution suitable for displaying on a web page."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/webResImage> <http://www.w3.org/2000/01/rdf-schema#domain> <http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> .
<http://environment.data.gov.uk/def/bathing-water-profile/webResImage> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsStatement> <http://www.w3.org/2000/01/rdf-schema#label> "sewage treatment works outfalls statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "stwOutfallsStatement is used to relate a bathing water profile to a statement about details of any sewage treatment outfalls which may impact on a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/stwOutfallsStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .
<http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#label> "Bathing Water Profile"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#comment> "BathingWaterProfile is a class of bathing water profiles.  An Instance of this class is a specific version of an instance of an EnduringBathingWaterProfile."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityGeneralStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#label> "run-off general statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "localAuthorityGeneralStatement is used to relate a standard language collection to a brief statement about precipitation run-off from roads and pavements."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/eaInvestigationsStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/eaInvestigationsStatement> <http://www.w3.org/2000/01/rdf-schema#label> "EA investigations statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/eaInvestigationsStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "eaInvestigationsStatement is used to relate a bathing water profile to a statement about details of any Environment Agency investigations into water quality which have impacted on a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/eaInvestigationsStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/standardLanguageCollection> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/standardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#label> "standard langauge"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/standardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#comment> "standardLanguageCollection relates a bathing water profile to a collection of standard or boilerplate language included in the profile."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/standardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#domain> <http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> .
<http://environment.data.gov.uk/def/bathing-water-profile/standardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#range> <http://environment.data.gov.uk/def/bathing-water-profile/StandardLanguageCollection> .
<http://environment.data.gov.uk/def/bathing-water-profile/standardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsStatement> <http://www.w3.org/2000/01/rdf-schema#label> "emergency and storm overflow outfalls statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "esoOutfallsStatement is used to relate a bathing water profile to a statement about details of any emergency outfalls and storm overflow outfalls, which may impact on a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/esoOutfallsStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/streamsRiversStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/streamsRiversStatement> <http://www.w3.org/2000/01/rdf-schema#label> "streams and rivers statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/streamsRiversStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "streamsRiversStatement is used to relate a bathing water profile to a statement about details of streams and rivers that impact water quality at a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/streamsRiversStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityStatement> <http://www.w3.org/2000/01/rdf-schema#label> "working with local authority statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "localAuthorityStatement is used to relate a bathing water profile to a statement about details of any work or improvements to water quality undertaken with the local authority which may impact on a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/localAuthorityStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/applicableYear> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/applicableYear> <http://www.w3.org/2000/01/rdf-schema#label> "year" .
<http://environment.data.gov.uk/def/bathing-water-profile/applicableYear> <http://www.w3.org/2000/01/rdf-schema#comment> "applicableYear relates a bathing water profile to the year to the year to which it applies, which typically is the year of publication."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/applicableYear> <http://www.w3.org/2000/01/rdf-schema#domain> <http://environment.data.gov.uk/def/bathing-water-profile/BathingWaterProfile> .
<http://environment.data.gov.uk/def/bathing-water-profile/applicableYear> <http://www.w3.org/2000/01/rdf-schema#range> <http://reference.data.gov.uk/def/intervals/Year> .
<http://environment.data.gov.uk/def/bathing-water-profile/applicableYear> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithPrivateOwnersStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithPrivateOwnersStatement> <http://www.w3.org/2000/01/rdf-schema#label> "working with private owners statement" .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithPrivateOwnersStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "workingWithPrivateOwnersStatement is used to relate a bathing water profile to a statement about details of any work or improvements to water quality undertaken with private owners which may impact on a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithPrivateOwnersStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/EnduringBathingWaterProfile> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .
<http://environment.data.gov.uk/def/bathing-water-profile/EnduringBathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#label> "Enduring Bathing Water Profile"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/EnduringBathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#comment> "EnduringBathingWaterProfile is a class of enduring bathing water profiles.  An instance of BathingWaterProfile is a version of an instance of EnduringBathingWaterProfile."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/EnduringBathingWaterProfile> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithIndustryStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithIndustryStatement> <http://www.w3.org/2000/01/rdf-schema#label> "working with industry statement" .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithIndustryStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "workingWithIndustryStatement is used to relate a bathing water profile to a statement about details of any work or improvements to water quality undertaken with local industry which may impact on a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/workingWithIndustryStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/algaeGeneralStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/algaeGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#label> "algae general statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/algaeGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "algaeGeneralStatement is used to relate a standard language collection to a brief statement about Algae in general at bathing waters."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/algaeGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/misconnectionsStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/misconnectionsStatement> <http://www.w3.org/2000/01/rdf-schema#label> "misconnections statement"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/misconnectionsStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "misconnectionsStatement is used to relate a bathing water profile to a brief statement about misconnections and any details specific to a bathing water."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/misconnectionsStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/pollutionManagementGeneralStatement> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/pollutionManagementGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#label> "pollution management statement" .
<http://environment.data.gov.uk/def/bathing-water-profile/pollutionManagementGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#comment> "pollutionManagementGeneralStatement is used to relate a standard language collection to a brief statement of how the Environment Agency manages pollution at bathing waters."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/pollutionManagementGeneralStatement> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/countyName> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
<http://environment.data.gov.uk/def/bathing-water-profile/countyName> <http://www.w3.org/2000/01/rdf-schema#label> "region"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/countyName> <http://www.w3.org/2000/01/rdf-schema#comment> "countyName relates a resource to an informal name for the county in which it is located, e.g. Devon.  It is used to associate a bathing water profile with a common name for the county containing the bathing water.  This name may differ slightly from the names published by reference authorities such as the Ordnance Survey."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/countyName> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
<http://environment.data.gov.uk/def/bathing-water-profile/StandardLanguageCollection> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .
<http://environment.data.gov.uk/def/bathing-water-profile/StandardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#label> "Bathing Water Profile Standard Language Collection"@en .
<http://environment.data.gov.uk/def/bathing-water-profile/StandardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#comment> "StandardLanguageCollection is a class of collections of boiler plate or standard text that is included in bathing water profile."@en .
<http://environment.data.gov.uk/def/bathing-water-profile/StandardLanguageCollection> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <http://environment.data.gov.uk/sources/def/def-bwp.ttl> .
}
